[g1]
nn1 ansible_host=16.16.202.187 ansible_user=admin ansible_ssh_private_key_file=/home/centos/mylesec2.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'
nn2 ansible_host=51.20.73.254 ansible_user=centos ansible_ssh_private_key_file=/home/centos/mylesec2.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'


[g2]
n3 ansible_host=51.20.128.43 ansible_user=centos ansible_ssh_private_key_file=/home/centos/mylesec2.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'
n4 ansible_host=51.20.95.51 ansible_user=centos ansible_ssh_private_key_file=/home/centos/mylesec2.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'
