# ansible n1 -m file -a "path=/home/centos/n1_dir state=directory"
---
- name: install httpd server
  hosts: nn1
  become: true
  tasks:
  - name: apache installed
    ansible.builtin.apt:
     name: apache2
     update_cache: true
     state: latest
  - name: custom index.html
    ansible.builtin.copy:
     dest: "/var/www/html/index.html"
     content:
        custom web page
...